package com.ciklum.lottoland.steps;

import com.ciklum.lottoland.data.DataGenerator;
import com.ciklum.lottoland.data.factories.DataGeneratorFactory;
import com.ciklum.lottoland.steps.serenity.UserRegistrationSteps;
import com.ciklum.lottoland.steps.serenity.VerificationSteps;
import cucumber.api.java.en.Given;
import cucumber.api.java.en.Then;
import cucumber.api.java.en.When;
import net.thucydides.core.annotations.Steps;

public class RegistrationSteps {

    @Steps
    private UserRegistrationSteps endUser;

    @Steps
    private VerificationSteps verificationSteps;

    @Given("the user is on the Registration page")
    public void givenTheUserIsOnTheRegistrationPage() {
        endUser.isOnRegistrationPage();
    }

    @When("the user enters data generated by '(.*)' generator")
    public void whenUserEntersFullName(String generator) {

        DataGenerator dg = DataGeneratorFactory.getInstance(generator);

        String[] fullName = dg.generateFullName().split(" ");
        endUser.entersFullName(fullName[0],fullName[fullName.length-1]);
        endUser.entersAddress(dg.generateAddress());
        endUser.entersEmail(dg.generateEmail());
        endUser.entersPhone(dg.generatePhone());
        endUser.selectsGender(dg.generateGender(endUser.getAllGenderOptions()));
        endUser.selectsHobbies(dg.generateHobbies(endUser.getAllHobbies()));
        endUser.selectsLenguages(dg.generateLanguages(endUser.getAllLanguages()));
        endUser.selectsSkills(dg.generateSkills(endUser.getAllSkills()));
        endUser.selectsCountries(dg.generateCountries(endUser.getAllCountries()));
        endUser.selectsCountry(dg.generateCountry(endUser.getAllCountryValues()));
        endUser.selectsYear(dg.generateYear(endUser.getAllYears()));
        endUser.selectsMonth(dg.generateMonth(endUser.getAllMonths()));
        endUser.selectsDay(dg.generateDay(endUser.getAllDays()));
        endUser.entersPassword(dg.generatePassword());
        endUser.entersPasswordConfirmation(dg.generatePasswordConfirmation());
        endUser.uploadsPhoto(dg.generatePhoto());
        endUser.pressesSubmitButton();
    }

    @Then("the new user should be registered '(.*)'")
    public void thenUserIsRegistered(boolean registered){
        verificationSteps.verifyUserRegistration(registered);
    }

}
