package com.ciklum.lottoland.steps;

import com.ciklum.lottoland.data.DataGenerator;
import com.ciklum.lottoland.data.factories.DataGeneratorFactory;
import com.ciklum.lottoland.steps.serenity.UserRegistrationSteps;
import com.ciklum.lottoland.steps.serenity.VerificationSteps;
import net.thucydides.core.annotations.Steps;
import org.jbehave.core.annotations.Given;
import org.jbehave.core.annotations.Then;
import org.jbehave.core.annotations.When;

public class RegistrationSteps {

    @Steps
    UserRegistrationSteps endUser;

    @Steps
    VerificationSteps verificationSteps;

    @Given("the user is on the Registration page")
    public void givenTheUserIsOnTheRegistrationPage() {
        endUser.isOnRegistrationPage();
    }

    @When("the user enters data generated by $generator")
    public void whenUserEntersFullName(String generator) {

        DataGenerator dg = DataGeneratorFactory.getInstance(generator);

        String[] fullName = dg.generateFullName().split(" ");
        endUser.entersFullName(fullName[0],fullName[fullName.length-1]);
        endUser.entersAddress(dg.generateAddress());
        endUser.entersEmail(dg.generateEmail());
        endUser.entersPhone(dg.generatePhone());
        endUser.selectsGender(dg.generateGender());
        endUser.selectsHobbies(dg.generateHobbies(endUser.getAllHobbies()));
//        endUser.selectsLenguages(dg.generateLanguages());
        endUser.selectsSkills(dg.generateSkills());
        endUser.selectsCountries(dg.generateCountries());
        endUser.selectsCountry(dg.generateCountry());
        endUser.selectsDateOfBirth(dg.generateDateOfBirth());
        endUser.entersPassword(dg.generatePassword());
        endUser.entersPasswordConfirmation(dg.generatePasswordConfirmation());
        endUser.uploadsPhoto(dg.generatePhoto());
        endUser.pressesSubmitButton();
    }

    @Then("the new user should be registered $registered")
    public void thenUserIsRegistered(boolean registered){
        verificationSteps.verifyUserRegistration(registered);
    }

}
